# Generated by Django 3.2.7 on 2022-04-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
    ]
